// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMvraR3TknlE1tiekJsWsWFFsgwIRyFq8',
    appId: '1:903304887583:web:7aa71a7ff03ee547a8842a',
    messagingSenderId: '903304887583',
    projectId: 'fir-4b304',
    authDomain: 'fir-4b304.firebaseapp.com',
    storageBucket: 'fir-4b304.appspot.com',
    measurementId: 'G-HQNK9CVC7Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVBB6cNkcPoxOGQj9vFJLv0RV9ZG7kCXE',
    appId: '1:903304887583:android:1312ef98a27af91ca8842a',
    messagingSenderId: '903304887583',
    projectId: 'fir-4b304',
    storageBucket: 'fir-4b304.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLVsrQOot06tuNAuF3QlmheXGlZAo3BoI',
    appId: '1:903304887583:ios:ab82e3dc8f400725a8842a',
    messagingSenderId: '903304887583',
    projectId: 'fir-4b304',
    storageBucket: 'fir-4b304.appspot.com',
    iosBundleId: 'com.example.blogger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLVsrQOot06tuNAuF3QlmheXGlZAo3BoI',
    appId: '1:903304887583:ios:b16105d797d92ecfa8842a',
    messagingSenderId: '903304887583',
    projectId: 'fir-4b304',
    storageBucket: 'fir-4b304.appspot.com',
    iosBundleId: 'com.example.blogger.RunnerTests',
  );
}
